export const detailsContainer: string;
export const menu_enter: string;
export const menu_enterActive: string;
export const menu_exit: string;
export const menu_exitActive: string;
export const details_enter: string;
export const details_enterActive: string;
export const details_exit: string;
export const details_exitActive: string;
